### ISSUE TITLE
Please make text font and size consistent on all <divs>

### ISSUE THREAD

**Issue by ctava** [gnyi/US-Gym-GNYI#8]

**Comment by glappen** [comment]
@ctava - Can you say a little more about this - it's not clear what font size you want on which divs.  Also, some text sizing is being done via <font size="x"></font> blocks which should probably be converted to divs.  

A related thought: would you be open to using something like bootstrap or zurb foundation to give us a basic grid system and css framework?

**Comment by ctava** [comment]
@glappen we might want to font used in the baked in image:
https://github.com/gnyi/US-Gym-GNYI/blob/gh-pages/images/gnyi-17-savethedate.jpg (not sure what it is though)

kindly make the sizes consistent based on the div, css etc

am totally open to using bootstrap 4. site needs to stay responsive, mobile friendly:
https://v4-alpha.getbootstrap.com/getting-started/introduction/#responsive-meta-tag
https://v4-alpha.getbootstrap.com/ (happy to experiment with alpha version too)

we could throw some of these in there too:
http://fontawesome.io/icons/

for example:
user icon for registration
list icon where there is a list
mail icons for email links
New monetary incentives == gifts

**Comment by ctava** [comment]
@glappen looking more into this, the `main.css` file already has font-family. `index.html` should be using the font and styling from main.css. Kindly get the two files to be in sync. with one another. Meaning, `index.html` should be respecting/using the styling from `main.css` . Is this something that you can get fixed up this week?


`font-family: 'Helvetica', sans-serif;

font-family: "freight-text-pro",Georgia,Cambria,"Times New Roman",Times,serif;`

**Comment by ctava** [comment]
so, please choose font-family and styling and we can have gnyi-17-savethedate.jpg adjusted accordingly...

**Comment by glappen** [comment]
@ctava - Sorry it took so long, but I finally sorted this out.  I stripped all the font tags out of the html, so that sizing is only controlled by the css now. I next got rid of the other fonts in css, so it's now all Helvetica.  Finally, I made the main content div wider and made all the fonts bigger in an attempt to make the site looks bit more modern.  Not sure how successful I was, but I think it's better.  Please review on my server before I push it live - it's a bit different and don't want to make the change before you get a chance to review.  URL is http://terminus.lapcominc.com:8000

Thanks!

**Comment by ctava** [comment]
@glappen looks good. push it live.
